steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build docker image for model training'
    args: [
      'build',
      '.',
      '-t',
      'europe-west1-docker.pkg.dev/$PROJECT_ID/mlops-docker-repo/model-training',
      '-f',
      'dockerfiles/train.dockerfile'
    ]
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push docker image for model training'
    args: [
      'push',
      'europe-west1-docker.pkg.dev/$PROJECT_ID/mlops-docker-repo/model-training'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build docker image for inference service'
    args: [
      'build',
      '.',
      '-t',
      'europe-west1-docker.pkg.dev/$PROJECT_ID/mlops-docker-repo/inference_service',
      '-f',
      'dockerfiles/api.dockerfile'
    ]
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push docker image for inference service'
    args: [
      'push',
      'europe-west1-docker.pkg.dev/$PROJECT_ID/mlops-docker-repo/inference_service'
    ]
