_wandb:
    value:
        cli_version: 0.19.2
        m: []
        python_version: 3.12.4
        t:
            "1":
                - 1
                - 41
                - 55
                - 105
            "2":
                - 1
                - 41
                - 55
                - 105
            "3":
                - 16
                - 23
                - 55
            "4": 3.12.4
            "5": 0.19.2
            "8":
                - 5
            "12": 0.19.2
            "13": linux-x86_64
architecture:
    value: ResNet
dataset:
    value: Hotdog/notHodog
epochs:
    value: 2
learning_rate:
    value: 0.001
