site_name: mlops-project-group88
site_author: Lin zhu, Boyang Xu, Wenji Xie
docs_dir: source


theme:
  language: en
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - search.suggest
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode


nav:
  - Home: 
    - index.md
  - Guide:
    - documents/guide.md
  - API documentation:
    - documents/api.md
  - About:
    - documents/contributing.md
  # - MY API:
  #   - documents/my_api.md


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - tables
  - attr_list
  - md_in_html

plugins:
- search
- mkdocstrings:
    handlers:
      python:
        options:
          show_root_heading: true
          separate_signature: true
          show_signature_annotations: true
